# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'comparador_interface.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QMainWindow,
    QMenu, QMenuBar, QPlainTextEdit, QProgressBar,
    QPushButton, QScrollBar, QSizePolicy, QStatusBar,
    QTimeEdit, QWidget)

class main_window(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(788, 460)
        MainWindow.setStyleSheet(u"")
        self.actionAbrir_db_txt = QAction(MainWindow)
        self.actionAbrir_db_txt.setObjectName(u"actionAbrir_db_txt")
        self.actionAbrir_alertas_txt = QAction(MainWindow)
        self.actionAbrir_alertas_txt.setObjectName(u"actionAbrir_alertas_txt")
        self.actionSalir = QAction(MainWindow)
        self.actionSalir.setObjectName(u"actionSalir")
        self.actionEliminar_db_txt = QAction(MainWindow)
        self.actionEliminar_db_txt.setObjectName(u"actionEliminar_db_txt")
        self.actionEliminar_alertas_txt = QAction(MainWindow)
        self.actionEliminar_alertas_txt.setObjectName(u"actionEliminar_alertas_txt")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.NombreProducto = QPlainTextEdit(self.centralwidget)
        self.NombreProducto.setObjectName(u"NombreProducto")
        self.NombreProducto.setGeometry(QRect(10, 20, 171, 351))
        self.Alert = QPlainTextEdit(self.centralwidget)
        self.Alert.setObjectName(u"Alert")
        self.Alert.setGeometry(QRect(510, 20, 261, 351))
        self.Precio = QPlainTextEdit(self.centralwidget)
        self.Precio.setObjectName(u"Precio")
        self.Precio.setGeometry(QRect(190, 20, 91, 351))
        self.URL = QPlainTextEdit(self.centralwidget)
        self.URL.setObjectName(u"URL")
        self.URL.setGeometry(QRect(290, 20, 211, 351))
        self.stop_button = QPushButton(self.centralwidget)
        self.stop_button.setObjectName(u"stop_button")
        self.stop_button.setGeometry(QRect(710, 390, 61, 23))
        self.play_button = QPushButton(self.centralwidget)
        self.play_button.setObjectName(u"play_button")
        self.play_button.setGeometry(QRect(630, 390, 75, 23))
        self.progresoBar = QProgressBar(self.centralwidget)
        self.progresoBar.setObjectName(u"progresoBar")
        self.progresoBar.setGeometry(QRect(490, 390, 118, 23))
        self.progresoBar.setAutoFillBackground(False)
        self.progresoBar.setValue(24)
        self.nameProgreso = QLabel(self.centralwidget)
        self.nameProgreso.setObjectName(u"nameProgreso")
        self.nameProgreso.setGeometry(QRect(430, 390, 47, 13))
        self.sleepTime = QTimeEdit(self.centralwidget)
        self.sleepTime.setObjectName(u"sleepTime")
        self.sleepTime.setGeometry(QRect(80, 390, 118, 22))
        self.nameTemporizador = QLabel(self.centralwidget)
        self.nameTemporizador.setObjectName(u"nameTemporizador")
        self.nameTemporizador.setGeometry(QRect(10, 390, 71, 16))
        self.sleep_button = QPushButton(self.centralwidget)
        self.sleep_button.setObjectName(u"sleep_button")
        self.sleep_button.setGeometry(QRect(210, 390, 75, 23))
        self.nombre_vertical = QScrollBar(self.centralwidget)
        self.nombre_vertical.setObjectName(u"nombre_vertical")
        self.nombre_vertical.setGeometry(QRect(160, 30, 20, 321))
        self.nombre_vertical.setOrientation(Qt.Vertical)
        self.precio_vertical = QScrollBar(self.centralwidget)
        self.precio_vertical.setObjectName(u"precio_vertical")
        self.precio_vertical.setGeometry(QRect(260, 30, 20, 321))
        self.precio_vertical.setOrientation(Qt.Vertical)
        self.nombre_horizontal = QScrollBar(self.centralwidget)
        self.nombre_horizontal.setObjectName(u"nombre_horizontal")
        self.nombre_horizontal.setGeometry(QRect(10, 350, 161, 16))
        self.nombre_horizontal.setOrientation(Qt.Horizontal)
        self.precio_horizontal = QScrollBar(self.centralwidget)
        self.precio_horizontal.setObjectName(u"precio_horizontal")
        self.precio_horizontal.setGeometry(QRect(200, 350, 71, 16))
        self.precio_horizontal.setOrientation(Qt.Horizontal)
        self.url_horizontal = QScrollBar(self.centralwidget)
        self.url_horizontal.setObjectName(u"url_horizontal")
        self.url_horizontal.setGeometry(QRect(290, 350, 201, 16))
        self.url_horizontal.setOrientation(Qt.Horizontal)
        self.url_vertical = QScrollBar(self.centralwidget)
        self.url_vertical.setObjectName(u"url_vertical")
        self.url_vertical.setGeometry(QRect(480, 30, 20, 311))
        self.url_vertical.setOrientation(Qt.Vertical)
        self.alerta_vertical = QScrollBar(self.centralwidget)
        self.alerta_vertical.setObjectName(u"alerta_vertical")
        self.alerta_vertical.setGeometry(QRect(750, 30, 20, 311))
        self.alerta_vertical.setOrientation(Qt.Vertical)
        self.alerta_horizontal = QScrollBar(self.centralwidget)
        self.alerta_horizontal.setObjectName(u"alerta_horizontal")
        self.alerta_horizontal.setGeometry(QRect(510, 350, 251, 16))
        self.alerta_horizontal.setOrientation(Qt.Horizontal)
        self.producto_name = QGroupBox(self.centralwidget)
        self.producto_name.setObjectName(u"producto_name")
        self.producto_name.setGeometry(QRect(50, 0, 61, 16))
        self.precio_name = QGroupBox(self.centralwidget)
        self.precio_name.setObjectName(u"precio_name")
        self.precio_name.setGeometry(QRect(200, 0, 81, 16))
        self.url_name = QGroupBox(self.centralwidget)
        self.url_name.setObjectName(u"url_name")
        self.url_name.setGeometry(QRect(380, 0, 31, 16))
        self.alerta_name = QGroupBox(self.centralwidget)
        self.alerta_name.setObjectName(u"alerta_name")
        self.alerta_name.setGeometry(QRect(620, 0, 61, 16))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 788, 21))
        self.menuArchivo = QMenu(self.menubar)
        self.menuArchivo.setObjectName(u"menuArchivo")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menuArchivo.addAction(self.actionAbrir_db_txt)
        self.menuArchivo.addAction(self.actionAbrir_alertas_txt)
        self.menuArchivo.addAction(self.actionEliminar_db_txt)
        self.menuArchivo.addAction(self.actionEliminar_alertas_txt)
        self.menuArchivo.addAction(self.actionSalir)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionAbrir_db_txt.setText(QCoreApplication.translate("MainWindow", u"Abrir db.txt", None))
        self.actionAbrir_alertas_txt.setText(QCoreApplication.translate("MainWindow", u"Abrir alertas.txt", None))
        self.actionSalir.setText(QCoreApplication.translate("MainWindow", u"Salir", None))
        self.actionEliminar_db_txt.setText(QCoreApplication.translate("MainWindow", u"Eliminar db.txt", None))
        self.actionEliminar_alertas_txt.setText(QCoreApplication.translate("MainWindow", u"Eliminar alertas.txt", None))
        self.NombreProducto.setPlainText("")
        self.Alert.setPlainText("")
        self.Precio.setPlainText("")
        self.URL.setPlainText("")
        self.stop_button.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.play_button.setText(QCoreApplication.translate("MainWindow", u"Play", None))
        self.nameProgreso.setText(QCoreApplication.translate("MainWindow", u"Progreso", None))
        self.nameTemporizador.setText(QCoreApplication.translate("MainWindow", u"Temporizador", None))
        self.sleep_button.setText(QCoreApplication.translate("MainWindow", u"Aceptar", None))
        self.producto_name.setTitle(QCoreApplication.translate("MainWindow", u"Producto", None))
        self.precio_name.setTitle(QCoreApplication.translate("MainWindow", u"Precio", None))
        self.url_name.setTitle(QCoreApplication.translate("MainWindow", u"URL", None))
        self.alerta_name.setTitle(QCoreApplication.translate("MainWindow", u"Alerta", None))
        self.menuArchivo.setTitle(QCoreApplication.translate("MainWindow", u"Archivo", None))
    # retranslateUi

